### ISSUE TITLE
Reporting PDtoMSstatsTMTFormat error with PTM data

### ISSUE THREAD

**Issue by lyons89** [Vitek-Lab/MSstatsConvert#79] opened 2023-07-11 17:21 UTC
Hello,

I just tracked down an error I was having when converting phosphoproteomics data output from PD using the PDtoMSstatsTMTFormat function. I kept getting the error

```
Error in .mergeAnnotation(input, annotation) : 
  ** Please check the annotation file. The channel name must be matched with that in input data.
```
I looked through my annotation file for awhile, but finally tracked down the issue being the lack of the "Annotated Sequence" column in the PD PSMs export file.

**Comment by tonywu1999** [comment] 2024-01-12 22:05
@lyons89

Thanks for bringing this issue to our attention.  I was able to reproduce the issue on my end as well, and it looks like we will need to add a better validation message for cases where the PD PSMs export file is missing columns.  

I'll look into pushing out some code to add this validation.

**Comment by tonywu1999** [comment] 2024-02-22 17:02
Going to close this issue since the fix is merged.  We'll be pushing the change to Bioconductor soon, but the validation change is available on Github.

**Closed by tonywu1999** 2024-02-22 17:02 UTC
